### PR TITLE
support minimonkey model

### PR DESCRIPTION
**Pull request by white2018**
This PR is intended to support minimonkey model. Note that vision_qna.py is automatically modified in lines containing only whitespace by pre-commit.

### CODE REVIEW

**Comment by matatonic** [comment]
Great, thank you! I missed this one.

**Comment by white2018** [comment]
> Great, thank you! I missed this one.

I am happy to do it. If any problem happens for merging, please let me know. @matatonic

**Comment by matatonic** [comment]
FYI, you have a typo in the model name. 'MiniMokney'

**Comment by white2018** [comment]
> FYI, you have a typo in the model name. 'MiniMokney'

@matatonic You are right. MiniMokney is committed. Thanks

**Comment by matatonic** [comment]
Merged into 0.33.0

**Comment by matatonic** [comment]
I took some liberties and implemented streaming also

**Comment by matatonic** [comment]
I contacted the modem maker also, and they renamed the repo to MiniMonkey, so all good now.

**Comment by white2018** [comment]
That's the best solution.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "matatonic/openedai-vision"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月23日(星期一) 凌晨5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [matatonic/openedai-vision] support minimonkey model (PR #18)





 
I contacted the modem maker also, and they renamed the repo to MiniMonkey, so all good now.

**Pull request closed without merging**
